### ISSUE TITLE
sanitize rpaths

### ISSUE THREAD

**Issue by isuruf** [matthew-brett/delocate#101]
In `gfortran-darwin-arm64` toolchain, I had accidentally kept absolute rpaths like `/Users/isuruf/miniforge3/lib` in there and delocate didn't do anything. (I've since fixed it). If we had released numpy wheels with these, anybody who could manipulate `/Users/isuruf/miniforge3/lib` can inject code. It's good to sanitize these absolute rpaths to avoid security issues like these.

cc @mattip

**Comment by HexDecimal** [comment]
Is there a good way to determine which paths are intended verses which paths are superfluous?

Is it as simple as blacklisting user directories or whitelisting system directories?

Are all relative paths okay?  Or should anything that doesn't start with `@loader_path` or `@executable_path` be removed?  Should only relative paths starting with `@loader_path` be allowed?  Should paths with `@executable_path` be replaced with `@loader_path`?

Should there be multiple sanitation levels or options?  What should be the default?

What are the existing tools doing about this kind of issue?

**Comment by isuruf** [comment]
We should definitely blacklist user directories. Other absolute directories like `/opt` might be okay, but that wouldn't really make the wheel relocatable. So, I think we should blacklist any absolute rpaths and maybe have an option to disable it.

**Comment by HexDecimal** [comment]
> So, I think we should blacklist any absolute rpaths and maybe have an option to disable it.

That could work.  I was thinking you couldn't blacklist a path like `/System/Library` but now I'm not sure if anything depends on those without linking to them directly (without using rpaths.)

**Comment by isuruf** [comment]
For `/System/Library`, you don't need rpath. Dynamic loader will look at those paths irrespective of rpaths.

**Comment by mattip** [comment]
Would the next step be to use `--sanitize-paths` in invocations of delocate in multibuild and cibuildwheel?

**Comment by HexDecimal** [comment]
Yes, after the new version is released. Which I'll do in a moment.

**Comment by HexDecimal** [comment]
New version released. It's optional right now with `--sanitize-paths`. I was too paranoid to make it the default, but maybe it should be.

I only know of my own use-case which is to use temporarily link a path for delocate to find the library at. The current tests are for this case.

**Comment by joerick** [comment]
Hello! @minrk just suggested we add this as a default to cibuildwheel. I was thinking, if this is accepted best practice, why not make it the default here? It would make things so much more simple for our users if our defaults are also your defaults. In fact, it gets kinda messy if these defaults get out of sync - e.g. a user that already has customised a delocate command won't get the new behaviour, and people copy/pasting from an old config won't realise they're opting-out of the new behaviour by omitting the flag.

**Comment by HexDecimal** [comment]
I should've make it opt-out with `--no-sanitize-paths` instead of opt-in, but there was nobody insisting on a specific behavior. I agree that it'd be best to make this consistent with other tools such as auditwheel.

**Comment by minrk** [comment]
Oops, I meant to also open #223 when I did the cibuildwheel PR, but got distracted.
