### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by keichi** [matthew-brett/delocate#104]
Could you please publish a new release? I currently have to install delocate from GitHub because my extension relies on `libstdc++` and https://github.com/matthew-brett/delocate/pull/76 is needed.

**Comment by matthew-brett** [comment]
Yes - sorry - overwhelmed at the moment - can you remind me early next
week, just in case I forget?

**Comment by keichi** [comment]
Of course, thanks!

**Comment by matthew-brett** [comment]
@HexDecimal - do you have a preferred email address to go in the AUTHORS file for the release?

**Comment by HexDecimal** [comment]
> @HexDecimal - do you have a preferred email address to go in the AUTHORS file for the release?

`4b796c65+github@gmail.com` is preferred.  My name should be updated from `Stewart` to `Kyle Benesch`.

**Comment by matthew-brett** [comment]
See #116 .

**Comment by matthew-brett** [comment]
Done - please test and confirm it's working?

**Comment by keichi** [comment]
Yes, 0.9.0 is working. Thanks!
