### ISSUE TITLE
Proposal - drop Pythons < 3.6

### ISSUE THREAD

**Issue by matthew-brett** [matthew-brett/delocate#109]
I propose that we drop all end-of-life Python releases for the master branch.  The oldest currently supported version is Python 3.6 - https://devguide.python.org/#status-of-python-branches

I don't think we have any reason to support very old Pythons - most users of delocate are release managers who will very likely have access to multiple versions of Python.

Any objections?

**Comment by HexDecimal** [comment]
I'd also suggest dropping i386 architectures from the tests.  Support for that architecture has been completely dropped by MacOS as they've moved on to ARM64.  As hard as it is to setup a MacOS environment it's much harder that it also has to be a super old one as well.

**Comment by matthew-brett** [comment]
Yes, dropping i386 is very sensible.

**Comment by matthew-brett** [comment]
i386 dropped as of merge of #111 

Signal that we are dropping Python < 3.6 in #113.
