### ISSUE TITLE
Python 3.10 OSX issues with pyproj

### ISSUE THREAD

**Issue by snowman2** [matthew-brett/delocate#131]
**Describe the bug**
Not entirely sure:
https://app.travis-ci.com/github/pyproj4/pyproj-wheels/jobs/547819498

```
ERROR:delocate.libsana:

@rpath/libproj.22.dylib not found:

  Needed by: /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmpoyvur5e4/wheel/pyproj/list.cpython-310-darwin.so

  Search path:

    

ERROR:delocate.libsana:@rpath/libproj.22.dylib not found, requested by /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmpoyvur5e4/wheel/pyproj/list.cpython-310-darwin.so

Traceback (most recent call last):

  File "/Users/travis/build/pyproj4/pyproj-wheels/venv/bin/delocate-wheel", line 8, in <module>

    sys.exit(main())

  File "/Users/travis/build/pyproj4/pyproj-wheels/venv/lib/python3.10/site-packages/delocate/cmd/delocate_wheel.py", line 91, in main

    copied = delocate_wheel(

  File "/Users/travis/build/pyproj4/pyproj-wheels/venv/lib/python3.10/site-packages/delocate/delocating.py", line 598, in delocate_wheel

    copied_libs = delocate_path(

  File "/Users/travis/build/pyproj4/pyproj-wheels/venv/lib/python3.10/site-packages/delocate/delocating.py", line 421, in delocate_path

    lib_dict = tree_libs_from_directory(

  File "/Users/travis/build/pyproj4/pyproj-wheels/venv/lib/python3.10/site-packages/delocate/libsana.py", line 375, in tree_libs_from_directory

    return _tree_libs_from_libraries(

  File "/Users/travis/build/pyproj4/pyproj-wheels/venv/lib/python3.10/site-packages/delocate/libsana.py", line 316, in _tree_libs_from_libraries

    raise delocate.delocating.DelocationError(

delocate.delocating.DelocationError: Could not find all dependencies.
```

**To Reproduce**
Handled by multibuild.

**Expected behavior**
Should automatically find it.

**Wheels used**
https://github.com/pyproj4/pyproj-wheels/pull/44

**Platform (please complete the following information):**
 - OSX
 - Delocate version: 0.10.0

**Comment by HexDecimal** [comment]
You might need to add the search path to the `extra_link_args` parameter of the `Extension` class.  For example, if the path of the library is `/usr/local/lib/libproj.22.dylib` then you should add the parameter:
```python
Extension(..., extra_link_args=["-rpath", "/usr/local/lib/"])
```
The ideal case is that there's a `pkg-config` script you can run to get the correct link arguments so you won't have to manually do this, but this is enough for simple libraries.

If your program can't find this library before you try to delocate it then this isn't a bug in Delocate.

**Comment by mwtoews** [comment]
In this case, get the library path using either `pkg-config proj --variable=libdir`, or if in a custom prefix `PROJ_DIR`:
```
projlibdir=$(PKG_CONFIG_PATH=$PROJ_DIR/lib/pkgconfig pkg-config proj --variable=libdir)
```

**Comment by HexDecimal** [comment]
Is `pkg-config  --libs` missing?  I might just be misunderstanding how it works.  `pkg-config proj --libs` should have the `-rpath` flags I assume.

Selecting the library is one step, that gets you the install name of `@rpath/libproj.22.dylib` when it's linked, but you also need to have the `-rpath` flags or else you won't find the library at runtime.  Delocate tries to find the library as if you ran the program, and having no rpaths when a library dependency has `@rpath/...` as its install path is a bad sign.

**Comment by snowman2** [comment]
Closing as I think this issue is unrelated to delocate. Thanks for your input!
