### ISSUE TITLE
Latest development main of wheel is missing pkginfo

### ISSUE THREAD

**Issue by henryiii** [matthew-brett/delocate#135]
**Describe the bug**
`wheel.pkginfo` was removed.

**To Reproduce**
Use an unreleased version of wheel.

**Expected behavior**
Not break.

**Wheels used**
The import is missing, so no need for a wheel.

**Platform (please complete the following information):**
 - OS version: any
 - Delocate version: any

**Additional context**

See: https://github.com/pypa/wheel/issues/433

**Comment by HexDecimal** [comment]
Thanks for bringing this up before the next release of wheel.
