### ISSUE TITLE
Proper way to locate python before using delocate-wheel?

### ISSUE THREAD

**Issue by DBraun** [matthew-brett/delocate#142]
Hi, my wheel involves a precompiled `.so` file on macOS. If I do `otool -L something.so` I see
`/Library/Frameworks/Python.framework/Versions/3.9/Python (compatibility version 3.9.0, current version 3.9.0)`

`delocate-listdeps` results in `/Library/Frameworks/Python.framework/Versions/3.9/Python`

After using `delocate-wheel --require-archs x86_64 -w repaired_wheel`, and installing it, I go to the site-packages folder and do `otool -L something.so` again:
`@loader_path/.dylibs/Python`
And there is a hidden folder `.dylibs` containing Python. delocate-wheel seems to have made this.

If I run my pytest locally, it works. However, with cibuildwheel, the pytest doesn't work. I think that this is due to cibuildwheel using a virtual environment, which might be in conflict with the lib at .dylibs/Python.

Is there a suggested way of linking against Python before using delocate-wheel?

A hacky thing I've done before is
`install_name_tool -change /Library/Frameworks/Python.framework/Versions/3.9/Python @executable_path/../../../../Python something.so` and then using delocate-wheel, which doesn't modify it.

In a normal Python installation without a virtual environment, @executable_path seems to resolve to `/Library/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/`
Therefore, `@executable_path/../../../../Python` resolves to `/Library/Frameworks/Python.framework/Versions/3.9/Python` and the pytest works. However, this trick doesn't work for virtual environments. I'm looking for a solution that works for both cases.

A little more background is here: https://github.com/pypa/cibuildwheel/discussions/991

**Comment by HexDecimal** [comment]
What do regular Python extensions do in this situation?  Surely a shared library bundled with Python itself doesn't need to be bundled again by a Python package to work.

Based on your posted issue it might be that your custom library `dawdreamer.so` does not link to Python the same way normal Python extensions do.  I don't know enough to be more specific.

**Comment by DBraun** [comment]
Thanks! I searched and found https://pybind11.readthedocs.io/en/stable/compiling.html

> On macOS: the build command is almost the same but it also requires passing the -undefined dynamic_lookup flag so as to ignore missing symbols when building the module

And the Xcode way involved `-Wl,-undefined,dynamic_lookup` although it's kind of an overreach to ignore all undefined symbols...
