### ISSUE TITLE
@rpath expansion fails

### ISSUE THREAD

**Issue by lericson** [matthew-brett/delocate#155]
We set `DYLD_LIBRARY_PATH` because of what appears to be a bug in `delocate`, the program that bundles up the shared library dependencies into the wheel file.

The linker makes a link like `@rpath/libmemcached.11.dylib` or similar, and delocate is unable to resolve this @rpath macro into /usr/local/lib for some reason, as it appears that delocate expects an LC_RPATH command to be listed by `otool -l _pylibmc....so`, which isn't happening.

This does not seem to be a problem for the DYLD system itself though, so again, likely a bug in delocate.

Temporary fix by hacking up DYLD_LIBRARY_PATH.

    env DYLD_LIBRARY_PATH=/usr/local/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}

**Comment by HexDecimal** [comment]
Sounds like `/usr/local/lib` is missing from the rpaths of the library, which if `@rpath/libmemcached.11.dylib` is supped to refer to that directory then the library is technically invalid.

You might want to add something like `-rpath /usr/local/lib` to the link flags when building the library so that it can link normally.  If you don't want to do that then setting `DYLD_LIBRARY_PATH` is the correct method.

Delocate should not make assumptions about missing rpaths.  It tries to follow normal linking rules as closely as possible.

**Comment by lericson** [comment]
It seems other tools (eg otool) look in `/usr/local` and other standard directories for `@rpath` references. I would suspect that is exactly why there is no LC_RPATH command to do so.

**Comment by lericson** [comment]
Here is the exact build steps executed by setuptools

    clang -Wno-unused-result \
          -Wsign-compare \
          -Wunreachable-code \
          -DNDEBUG \
          -g \
          -fwrapv \
          -O3 \
          -Wall \
          -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include \
          -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include \
          -DUSE_ZLIB \
          -I/Users/lericson/devel/pylibmc/env-3.10/include \
          -I/Users/lericson/.pyenv/versions/3.10.6/include/python3.10 \
          -c src/_pylibmcmodule.c \
          -o build/temp.macosx-11.6-x86_64-cpython-310/src/_pylibmcmodule.o \
          -fno-strict-aliasing \
          -std=c99

    clang -bundle \
          -undefined dynamic_lookup \
          -L/usr/local/opt/readline/lib \
          -L/usr/local/opt/readline/lib \
          -L/Users/lericson/.pyenv/versions/3.10.6/lib \
          -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib \
          -L/usr/local/opt/readline/lib \
          -L/usr/local/opt/readline/lib \
          -L/Users/lericson/.pyenv/versions/3.10.6/lib \
          -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib \
          build/temp.macosx-11.6-x86_64-cpython-310/src/_pylibmcmodule.o \
          -lmemcached \
          -lz \
          -o build/lib.macosx-11.6-x86_64-cpython-310/_pylibmc.cpython-310-darwin.so

(line-wrapped by me)

**Comment by lericson** [comment]
Sorry, distutils, not setuptool.s

**Comment by HexDecimal** [comment]
The search paths for rpaths are embedded in the library.  If a tool looks in `/usr/local` it's because `/usr/local` was added to that libraries rpaths.

`-rpath /usr/local/lib` adds the LC_RPATH for that directory.

**Comment by lericson** [comment]
If I understand you correctly, you mean Clang is producing "technically broken" dynamic libraries in the trivial usage I showed above?

**Comment by HexDecimal** [comment]
I think Clang might be expecting you to add an rpath like `@loader_path/lib` and then copy your dependencies into that relative folder manually.  If the library does not come pre-installed then it's your responsibility to manage it and you can hand that responsibility off to Delocate using whatever methods you want.

You can add `extra_link_args=["-rpath /usr/local/lib"]` to your extension.  Or you can accept that the library dependency is probably not portable and stick with using `DYLD_LIBRARY_PATH`.

After Delocate is done the end result is the same.  The dependency is bundled inside of the package and the link paths are changed to reflect that.

**Comment by lericson** [comment]
Alright, I think I don't quite understand but since I convinced delocate to do what I want, and delocate fixes the issue for everybody else, it's a non-issue.

I would be curious to know what the cause is though because from my end, all I have done is to install a library (libmemcached, CMake) and linked to it with distutils.

I suspect it's something to do with how libmemcached is made but I can't really tell -- if I add `-lzstd` or so which is also installed in `/usr/local`, I don't get these strange @rpath based link paths.

**Comment by HexDecimal** [comment]
Linking C/C++ libraries has always been a huge pain and rpaths add an extra complexity that's not on other platforms.

Really just make sure you run a test in an isolated environment so that you know your library will load correctly.

**Comment by lericson** [comment]
I think I know why this happens...

```
% otool -l /usr/local/lib/libmemcached.11.dylib
/usr/local/lib/libmemcached.11.dylib:
[…]
Load command 4
          cmd LC_ID_DYLIB
      cmdsize 56
         name @rpath/libmemcached.11.dylib (offset 24)
   time stamp 1 Thu Jan  1 01:00:01 1970
      current version 11.0.0
compatibility version 11.0.0
[…]
```

**Comment by lericson** [comment]
CMake is compiling with `-install_name @rpath/libmemcached.11.dylib`, so that is ultimately the reason.

In fact, it seems this will be a reoccurring problem:

https://cmake.org/cmake/help/latest/policy/CMP0042.html#policy:CMP0042

**Comment by lericson** [comment]
Alright, I think this concludes this issue -- I suspect more devs will need to know this going forward but closing since "it is the way it is." 

I simply add `-DCMAKE_MACOSX_RPATH:Bool=FALSE` to the CMake call.

**Comment by HexDecimal** [comment]
Yes.  Linking to a library causes the dependent library to use the install name id of the depended-on library to look for it.  If that install name is using `@rpath` then you have to add the directories that you expect to find that library in to your list of rpaths.  If it isn't using `@rpath` then you'll have even fewer options in how to define where the library exists at.

Having an install name of `@rpath/this_lib` is very reasonable if the library is not hardcoding its path.  There isn't a real alternative to this.  Using the old setting of CMake will make it harder to link the library.

You already had a working solution from the start and it's one of the 2 that I've suggested.  I don't have the energy to reiterate how MacOS dynamically links programs.

**Comment by lericson** [comment]
I just checked and as I suspected, _none_ of the other libraries in `/usr/local/lib` have `@rpath` in their `LC_ID_DYLIB` definition.

It makes no sense to put `@rpath` in the name of a system-wide installed library. Having `@rpath` in your `-install_name` means that the linking program needs to _a priori_ know where your library is, and adjust `-rpath` accordingly. This would completely defeat the purpose of the search path mechanism.

The "working solution", in my eyes, is a hack. The correct fix is to identify the source of this problem, which seems to be setting `-DCMAKE_INSTALL_NAME_DIR` to the install prefix (which is hinted at by the CMake documentation.)

**Comment by HexDecimal** [comment]
I wasn't aware of how the packaging for libraries in `/usr/local/lib` is supposed to work.  You're right, what I suggested is not for system-wide libraries, but for portable ones usually being built in-place.  CMake likely assumes it's being used in that way by default until some flag tells it otherwise.

If that's the case then maybe report it to the Memcached project.

**Comment by lericson** [comment]
I agree, it seems to be a mistake in this CMake-ified libmemcached -- https://github.com/awesomized/libmemcached -- but I'm not sure how to fix it. I just set the CMAKE_INSTALL_NAME_DIR to the prefix and that seems to work.

**Comment by HexDecimal** [comment]
The CMake script probably isn't wrong and doesn't need to be fixed directly.

If you installed it from Brew then the Brew formula is wrong and `CMAKE_INSTALL_NAME_DIR` should be set there, likely as a CLI flag.  I don't know the details of this or what the standards are.
