### ISSUE TITLE
comparison to `auditwheel`

### ISSUE THREAD

**Issue by johnyf** [matthew-brett/delocate#16]
The `delocate` package appears to be the OS X counterpart of [`auditwheel`](https://github.com/pypa/auditwheel), which is for Linux (and seems to have been a more recent development than `delocate`). It could be helpful to point to `auditwheel` from the README, in case one is interested in amending Linux wheels instead, or Linux wheels too. It may also be useful to briefly compare to `auditwheel` in terms of functionality.

**Comment by matthew-brett** [comment]
Right - actually auditwheel was half-fork of delocate and includes some delocate code.

Any interest in doing a quick PR to add the link in the README?

**Comment by johnyf** [comment]
Thank you for the explanation, I had not noticed https://github.com/pypa/auditwheel/commit/4562a2928cc6f20d162e102b53b950f8768e91ca. I opened a PR that adds the link to `auditwheel`.
