### ISSUE TITLE
Please describe `delocate-fuse` in the README

### ISSUE THREAD

**Issue by rgommers** [matthew-brett/delocate#169]
`delocate-fuse` seems like the easy to use command-line utility one needs to produce `universal2` wheels (thanks for adding it to this project Matthew!). It'd be great to have it described in the README, so it is easier to discover. Especially because I and others have been pointing people to it as the recommended way to get a `universal2` wheel from thin wheels. It seems like the CLI tool that `py2app` & co need.

**Comment by mattip** [comment]
Could you make a release with this and #167 so that NumPy (and maybe others) do not have to install from git?

**Comment by HexDecimal** [comment]
This is only a doc update, but I'll make a new release with #167.

**Comment by mattip** [comment]
Thanks

**Comment by HexDecimal** [comment]
@mattip delocate 0.10.4 has been released.

**Comment by mattip** [comment]
That was quick, thanks!
