### ISSUE TITLE
it would be nice if delocate-fuse would rename its output

### ISSUE THREAD

**Issue by glyph** [matthew-brett/delocate#174]
**Is your feature request related to a problem? Please describe.**
`delocate-fuse` creates a `universal2` wheel (which is amazing) but gives it the wrong tag

**Describe the solution you'd like**
Do not rewrite the input in place, instead, put a wheel next to it with a modified tag name.

**Describe alternatives you've considered**
It is not clear to me what other behavior would be correct :)

**Additional context**
I'm not sure if this is a feature or a bug. It strikes me as incorrect behavior to write an x86_64 tagged wheel that has arm64 code in it, but I am filing it as an enhancement as I assume the existing behavior has some reason for existing.

**Comment by matthew-brett** [comment]
I'm afraid the reason it hasn't changed is because - it started that way.    Would you be interested in changing it to give the correct tag instead, with a `--retag` optional flag to trigger that behavior (for back-compatibility)?

**Comment by Doondondon** [comment]
> **Is your feature request related to a problem? Please describe.** `delocate-fuse` creates a `universal2` wheel (which is amazing) but gives it the wrong tag
> 
> **Describe the solution you'd like** Do not rewrite the input in place, instead, put a wheel next to it with a modified tag name.
> 
> **Describe alternatives you've considered** It is not clear to me what other behavior would be correct :)
> 
> **Additional context** I'm not sure if this is a feature or a bug.
