### ISSUE TITLE
Error in building wheels for macos 

### ISSUE THREAD

**Issue by Earammak** [matthew-brett/delocate#178]
**Describe the bug**
We are trying to build whhels, getting the error. 
Looks like some dependent libraries are missing [ all the files are there, but not picking the right libraries (facing problem only for libdb2.dylib)].
**To Reproduce**
Used to build wheels from cibuildwheel. 
Command: cibuildwheel --plat macos 
While repairing wheels, could see the error from delocate.
Logs:
Repairing wheel...

+ delocate-wheel --require-archs x86_64 -w /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/cibw-run-9v4myjce/cp311-macosx_x86_64/repaired_wheel -v /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/cibw-run-9v4myjce/cp311-macosx_x86_64/built_wheel/ibm_db-3.1.4-cp311-cp311-macosx_10_17_x86_64.whl
Fixing: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/cibw-run-9v4myjce/cp311-macosx_x86_64/built_wheel/ibm_db-3.1.4-cp311-cp311-macosx_10_17_x86_64.whl
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2drdat
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2drdat
ERROR:delocate.libsana:../lib/libdb2.dylib not found, requested by /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2drdat
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2dsdcfgfill
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2dsdcfgfill
ERROR:delocate.libsana:../lib/libdb2.dylib not found, requested by /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2dsdcfgfill
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2support
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2support
ERROR:delocate.libsana:../lib/libdb2.dylib not found, requested by /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2support
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2trc
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2trc
ERROR:delocate.libsana:../lib/libdb2.dylib not found, requested by /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2trc
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2level
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2level
ERROR:delocate.libsana:../lib/libdb2.dylib not found, requested by /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2level
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2diag
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2diag
ERROR:delocate.libsana:../lib/libdb2.dylib not found, requested by /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2diag
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2cli
ERROR:delocate.libsana:
../lib/libdb2.dylib not found:
  Needed by: /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2cli
ERROR:delocate.libsana:../lib/libdb2.dylib not found, requested by /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/tmprjqtsfof/wheel/clidriver/bin/db2cli
Traceback (most recent call last):
  File "/private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/cibw-run-9v4myjce/cp311-macosx_x86_64/build/venv/bin/delocate-wheel", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/cibw-run-9v4myjce/cp311-macosx_x86_64/build/venv/lib/python3.11/site-packages/delocate/cmd/delocate_wheel.py", line 128, in main
    copied = delocate_wheel(
             ^^^^^^^^^^^^^^^
  File "/private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/cibw-run-9v4myjce/cp311-macosx_x86_64/build/venv/lib/python3.11/site-packages/delocate/delocating.py", line 651, in delocate_wheel
    copied_libs = delocate_path(
                  ^^^^^^^^^^^^^^
  File "/private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/cibw-run-9v4myjce/cp311-macosx_x86_64/build/venv/lib/python3.11/site-packages/delocate/delocating.py", line 473, in delocate_path
    lib_dict = tree_libs_from_directory(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/cibw-run-9v4myjce/cp311-macosx_x86_64/build/venv/lib/python3.11/site-packages/delocate/libsana.py", line 384, in tree_libs_from_directory
    return _tree_libs_from_libraries(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/cibw-run-9v4myjce/cp311-macosx_x86_64/build/venv/lib/python3.11/site-packages/delocate/libsana.py", line 325, in _tree_libs_from_libraries
    raise delocate.delocating.DelocationError(
delocate.delocating.DelocationError: Could not find all dependencies.

                                                             ✕ 25.29s
Error: Command delocate-wheel --require-archs x86_64 -w /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/cibw-run-9v4myjce/cp311-macosx_x86_64/repaired_wheel -v /private/var/folders/6_/95j14jg17h50bbc5dlx8h7l0s94p44/T/cibw-run-9v4myjce/cp311-macosx_x86_64/built_wheel/ibm_db-3.1.4-cp311-cp311-macosx_10_17_x86_64.whl failed with code 1. None

**Expected behavior**
Only for mac i could this error in building wheels. 
Other platforms was able to buld the wheels.

**Platform (please complete the following information):**
 - OS version: macOS 12 
 - Delocate version: 0.10.4

Thanks

**Comment by HexDecimal** [comment]
My assumptions: When building the Python library `libdb2` was linked using the path `../lib/libdb2.dylib`, and  `../lib/libdb2.dylib` is not found from the working directory where delocate-wheel is run from.

You must run the delocate command from a working directory which can link the dependencies the library was compiled with.  If you can't start python and import your library from a directory then you also can't delocate from there.

I'm not really sure how to handle libraries with unusual hard-coded install names.  Maybe add the libraries folder where `libdb2.dylib` is to `DYLD_LIBRARY_PATH`?

**Comment by Earammak** [comment]
@HexDecimal Thank you so much for your valuable input. Yes, that is the question here, why only this [libdb2.dylib] library giving the delocate error.
I also tried by setting DYLD_LIBRARY_PATH,and could see the same behavior.

Thannks
