### ISSUE TITLE
`delocate-wheel` fails on UnicodeDecodeError

### ISSUE THREAD

**Issue by brenthuisman** [matthew-brett/delocate#181]
### Description

See title. The command (`delocate-wheel`) errors out with `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 396537: invalid continuation byte`, see log.

There have been no changes to this package recently, so it might be an environmental thing, but the Github virtual env changelog doesn't show an obvious change. Any ideas?

### Build log

https://github.com/arbor-sim/arbor/actions/runs/4904892311/jobs/8758317425#step:7:10823

### CI config

https://github.com/arbor-sim/arbor/actions/runs/4904892311/workflow

**Comment by HexDecimal** [comment]
I'd guess that MacOS's `unzip` is behaving badly.  It isn't outputting in the locale set by Python for some reason.  I'm going to assume that `unzip` writes filenames correctly despite this.  I'd note that from the CI the same repair seems to work okay on Ubuntu and I recall having issues with MacOS zipping tools before as if they're outdated on MacOS compared to other OSes.

Could add `-q` to the `unzip` command which will suppress the output of filenames, or tell Python to replace or escape malformed characters.  The output here is only saved for debugging a failing command.

**Comment by brenthuisman** [comment]
A colleague sounded the all clear! Thanks!

**Comment by jvolkman** [comment]
Maybe consider borrowing `auditwheel`'s implementation which uses `zipfile` but also preserves file permissions. This would remove the dependency on the external `unzip`.

https://github.com/pypa/auditwheel/blob/321292d620f14ddc7ad3247d71746679d6e51558/src/auditwheel/tools.py#L31-L52
