### ISSUE TITLE
Unexpected first line error when trying to list deps

### ISSUE THREAD

**Issue by y0ast** [matthew-brett/delocate#21]
When trying to list the deps of a wheel I created I get the following error:

```
$ delocate-listdeps dlib-19.4.99-cp36-cp36m-macosx_10_12_x86_64.whl
Traceback (most recent call last):
  File "/Users/joost/anaconda/bin/delocate-listdeps", line 61, in <module>
    main()
  File "/Users/joost/anaconda/bin/delocate-listdeps", line 44, in main
    lib_dict = wheel_libs(path)
  File "/Users/joost/anaconda/lib/python3.5/site-packages/delocate/libsana.py", line 161, in wheel_libs
    lib_dict = tree_libs(tmpdir, filt_func)
  File "/Users/joost/anaconda/lib/python3.5/site-packages/delocate/libsana.py", line 54, in tree_libs
    for install_name in get_install_names(depending_libpath):
  File "/Users/joost/anaconda/lib/python3.5/site-packages/delocate/tools.py", line 173, in get_install_names
    if not _line0_says_object(lines[0], filename):
  File "/Users/joost/anaconda/lib/python3.5/site-packages/delocate/tools.py", line 143, in _line0_says_object
    raise InstallNameError('Unexpected first line: ' + line0)
delocate.tools.InstallNameError: Unexpected first line: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/private/var/folders/b5/hgpy98310bg_g3hfqngl759m0000gn/T/tmprtlon9sy/dlib/__init__.py': The file was not recognized as a valid object file
```

Running it directly on the scipy wheel from PyPi gives the same error.

I am wondering if the error is on my side or if there's something wrong with delocate.

**Comment by HexDecimal** [comment]
Any chance you could print out the `filename` parameter inside `_line0_says_object`?

**Comment by y0ast** [comment]
It's this: `/private/var/folders/b5/hgpy98310bg_g3hfqngl759m0000gn/T/tmppgljdoid/dlib/__init__.py`

**Comment by HexDecimal** [comment]
Looks like this issue is fixed in an unreleased commit https://github.com/matthew-brett/delocate/commit/da5a0f7c81a353e939344e27e59f15994bfb6b8f. The old code is expecting a period at the end of the line which doesn't show in your output.

For now, delocate should work if you install it directly from master.

**Comment by matthew-brett** [comment]
I've uploaded a new release with the fix.  Does it work for you now?

**Comment by y0ast** [comment]
Yes this works great! Thank @matthew-brett 

My wheel contains rpaths so eye'ing this PR: https://github.com/matthew-brett/delocate/pull/20
