### ISSUE TITLE
wheel renaming in `delocate` 0.11.0 breaks `google-re2` builds

### ISSUE THREAD

**Issue by junyer** [matthew-brett/delocate#213]
It seems that the wheel renaming in `delocate` 0.11.0 breaks `google-re2` builds. For example,

* On macOS 12 on X64, after we build the wheel with platform name `macosx-12.0-x86_64`, `delocate_wheel` renames the wheel from `google_re2-1.1-cp312-cp312-macosx_12_0_x86_64.whl` to `google_re2-1.1-cp312-cp312-macosx_13_1_x86_64.whl`.

* On macOS 13 on X64, after we build the wheel with platform name `macosx-13.0-x86_64`, `delocate_wheel` renames the wheel from `google_re2-1.1-cp312-cp312-macosx_13_0_x86_64.whl` to `google_re2-1.1-cp312-cp312-macosx_14_0_x86_64.whl`.

I discovered the issue tonight while running our GitHub Actions workflow, the pertinent step of which is configured [here](https://github.com/google/re2/blob/c0f9f1746f3e0d017eb5c2826a10bab1c04f598a/.github/workflows/python.yml#L103-L110). I don't understand why 12.0 becomes 13.1 and 13.0 becomes 14.0. Are we doing something wrong? Or **_not_** doing something that we should be doing?

Thanks in advance!

**Comment by HexDecimal** [comment]
Make sure the `env` has `MACOSX_DEPLOYMENT_TARGET=12.0` set for the first wheel and `MACOSX_DEPLOYMENT_TARGET=13.0` for the second wheel. This will cause Delocate to enforce those versions.

**Comment by HexDecimal** [comment]
Delocate's behavior has changed to set the MacOS version automatically based on the requirements of the bundled libraries. This may mean that previous wheels had incorrect MacOS tags and did not support the MacOS versions they claimed to support.

**Comment by junyer** [comment]
Many thanks for the swift reply! Setting `MACOSX_DEPLOYMENT_TARGET` resulted in errors like `delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 12.0: /private/var/folders/h1/8hndypj13nsbj5pn4xsnv1tm0000gn/T/tmp9g0rdicn/wheel/_re2.cpython-312-darwin.so has a minimum target of 13.1`. It turns out that we haven't been passing `--macos_minimum_os` to Bazel, which looks likely to be the root cause. (Mentioning https://github.com/bazelbuild/bazel/issues/16932 here for visibility...)
