### ISSUE TITLE
Getting Homebrew gfortran to work with fat / `intel` binary

### ISSUE THREAD

**Issue by dhermes** [matthew-brett/delocate#23]
This is more of a "here's a suggestion" than it is a bug report.

From the docs (I saw it on the PyPI long description), @matthew-brett says:

> In fact my scipy wheel is one such example, because I inadvertently linked against the homebrew libraries, which are x86_64 only.

Empirically, with 2.7 from Python.org, the wheel `scipy-0.19.1-cp27-cp27m-macosx_10_6_intel...whl` **does not** work in 32-bit mode:

```
$ arch -32 /Library/Frameworks/Python.framework/Versions/2.7/bin/python -c 'import scipy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/__init__.py", line 114, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/_lib/_ccallback_c.so, 2): no suitable image found.  Did find:
        /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/_lib/_ccallback_c.so: mach-o, but wrong architecture
```

If it is in fact because the Homebrew `gfortran` libraries that are `x86_64` only, I have a solution!

You can use `lipo` and `install_name_tool` to create two dual architecture dynamic libraries that do what you want.

## Inspect the `dylib`s

First, note that the dynamic library is single architecture, but it has a sibling:

```
$ (cd /usr/local/Cellar/gcc/7.2.0/lib/gcc/7/ && file libgfortran.4.dylib)
libgfortran.4.dylib: Mach-O 64-bit dynamically linked shared library x86_64
$ (cd /usr/local/Cellar/gcc/7.2.0/lib/gcc/7/i386/ && file libgfortran.4.dylib)
libgfortran.4.dylib: Mach-O dynamically linked shared library i386
```

To be comprehensive, we need to check the dependencies:

```
$ otool -L /usr/local/Cellar/gcc/7.2.0/lib/gcc/7/libgfortran.4.dylib
/usr/local/Cellar/gcc/7.2.0/lib/gcc/7/libgfortran.4.dylib:
        /usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib (compatibility version 5.0.0, current version 5.0.0)
        /usr/local/Cellar/gcc/7.2.0/lib/gcc/7/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
        /usr/local/lib/gcc/7/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
$ otool -L /usr/local/Cellar/gcc/7.2.0/lib/gcc/7/i386/libgfortran.4.dylib
/usr/local/Cellar/gcc/7.2.0/lib/gcc/7/i386/libgfortran.4.dylib:
        /usr/local/opt/gcc/lib/gcc/7/i386/libgfortran.4.dylib (compatibility version 5.0.0, current version 5.0.0)
        /usr/local/Cellar/gcc/7.2.0/lib/gcc/7/i386/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
        /usr/local/lib/gcc/7/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

We feel pretty secure about `libSystem`, so it's `libgcc_s` and `libquadmath` that we need to check out.

Happily, `libgcc_s` is already dual architecture:

```
$ (cd /usr/local/lib/gcc/7/ && file libgcc_s.1.dylib)
libgcc_s.1.dylib: Mach-O universal binary with 2 architectures
libgcc_s.1.dylib (for architecture x86_64):     Mach-O 64-bit dynamically linked shared library x86_64
libgcc_s.1.dylib (for architecture i386):       Mach-O dynamically linked shared library i386
```

`libquadmath` is in the same boat as `libgfortran` (i.e. single architecture)

```
$ (cd /usr/local/Cellar/gcc/7.2.0/lib/gcc/7/ && file libquadmath.0.dylib)
libquadmath.0.dylib: Mach-O 64-bit dynamically linked shared library x86_64
$ (cd /usr/local/Cellar/gcc/7.2.0/lib/gcc/7/i386/ && file libquadmath.0.dylib)
libquadmath.0.dylib: Mach-O dynamically linked shared library i386
```

but it has no more dependencies, so our dependency graph is "known":

```
$ otool -L /usr/local/Cellar/gcc/7.2.0/lib/gcc/7/libquadmath.0.dylib
/usr/local/Cellar/gcc/7.2.0/lib/gcc/7/libquadmath.0.dylib:
        /usr/local/opt/gcc/lib/gcc/7/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
        /usr/local/lib/gcc/7/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
$ otool -L /usr/local/Cellar/gcc/7.2.0/lib/gcc/7/i386/libquadmath.0.dylib
/usr/local/Cellar/gcc/7.2.0/lib/gcc/7/i386/libquadmath.0.dylib:
        /usr/local/opt/gcc/lib/gcc/7/i386/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
        /usr/local/lib/gcc/7/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

## Frankenstein's Monster

We can just create a dual architecture dynamic library for each of `libgfortran` and `libquadmath`. I'll show how to modify the `i386` libraries in excruciating detail, but will leave `x86_64` to the reader (it's essentially just copy-paste).

We prepare the `i386` dynamic libraries for modification

```
mkdir -p frankenstein/i386/
cp /usr/local/Cellar/gcc/7.2.0/lib/gcc/7/i386/libgfortran.4.dylib frankenstein/i386/
chmod 644 frankenstein/i386/libgfortran.4.dylib
cp /usr/local/Cellar/gcc/7.2.0/lib/gcc/7/i386/libquadmath.0.dylib frankenstein/i386/
chmod 644 frankenstein/i386/libquadmath.0.dylib
```

Then we update the `install_name` of each to the eventual location of the dual architecture version:

```
install_name_tool \
  -id $(pwd)/frankenstein/libgfortran.4.dylib \
  frankenstein/i386/libgfortran.4.dylib
install_name_tool \
  -id $(pwd)/frankenstein/libquadmath.0.dylib \
  frankenstein/i386/libquadmath.0.dylib
```

and also change the dependency in `libgfortran` to the eventual location of the dual architecture `libquadmath`:

```
install_name_tool \
  -change \
  /usr/local/Cellar/gcc/7.2.0/lib/gcc/7/i386/libquadmath.0.dylib \
  $(pwd)/frankenstein/libquadmath.0.dylib \
  frankenstein/i386/libgfortran.4.dylib
```

Now the dynamic libraries are done being edited:

```
chmod 444 frankenstein/i386/libgfortran.4.dylib
chmod 444 frankenstein/i386/libquadmath.0.dylib
```

After doing essentially the same thing in `frankenstein/x86_64` we are ready to create the final products. (The only real difference is that the subdirectory `i386/` is not in the Homebrew path.)

```
lipo \
  frankenstein/i386/libgfortran.4.dylib \
  frankenstein/x86_64/libgfortran.4.dylib \
  -create \
  -output frankenstein/libgfortran.4.dylib
lipo \
  frankenstein/i386/libquadmath.0.dylib \
  frankenstein/x86_64/libquadmath.0.dylib \
  -create \
  -output frankenstein/libquadmath.0.dylib
```

To make the linker happy, we create symlinks without versions:

```
(cd frankenstein/ && ln -s libgfortran.4.dylib libgfortran.dylib)
(cd frankenstein/ && ln -s libquadmath.0.dylib libquadmath.dylib)
```

From here, `delocate-wheel` has no issue with these dual architecture `frankenstein`s when using `--check-archs`.

I just uploaded three wheels created this way for a [package][2] of mine.

----

See also: [hack][1] to get dual architecture object files from the Homebrew `gfortran`.

[1]: https://github.com/scipy/scipy/issues/7564#issuecomment-325081445
[2]: https://pypi.org/project/bezier/0.5.0/#files

**Comment by matthew-brett** [comment]
Thanks for the exploration!  Actually, we used to build scipy wheels that were 32 and 64 bit, and we did it by building a 32-bit wheel, and a 64-bit wheel, and then fusing them into the same wheel with `delocate-fuse` - see https://github.com/MacPython/scipy-wheels/commit/b3b2317ab2ceb518d9f700a0d2e39971fb1843f4 for the commit removing the 32-bit builds.  Do you have need of the 32-bit builds?

**Comment by dhermes** [comment]
@matthew-brett I don't have need of the 32-bit builds.

I was just trying to be a good citizen and make sure the uploaded wheels for my package would work on both. When I was reading up on how to use `delocate`, I noticed that SciPy might be able to benefit. Instead it seems like I could benefit from RTFM and learning that `delocate-fuse` exists! Cheers.

**Comment by matthew-brett** [comment]
Ah no worries - no reason why you would have seen `delocate-fuse`.  We used to put a lot of energy into building and testing for both 32 and 64 bit, but it gradually seemed that there was no-one using these, and so the temptation to keep jumping through the hoops got less...

**Comment by dhermes** [comment]
Gotcha. Thanks for the info. I think we're all good to close this out if it's of no use to you / SciPy?

I do have a "closing" question if that's OK? Why is it acceptable to use `/DLC/` as a prefix for the `install_name` when you move libraries into `.dylibs`? (It might be worth documenting somewhere? I can send a PR if it makes sense to document in this project.)

**Comment by matthew-brett** [comment]
I think this issue, even if closed, will be a good source for people searching - so yes, feel free to close.

I chose /DLC/ as an unlikely actual file path, so that it would be more obvious that the install name is arbitrary, but for no deeper reason than that.  Yes please do PR with documention if you feel moved to do that, it would be helpful.

**Comment by dhermes** [comment]
Thanks for the info!
