### ISSUE TITLE
Allow rpath fallback to LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by fbrennen** [matthew-brett/delocate#24]
As I understand it, if the linker can't find a particular library relative to an entry in `@rpath`, then it will fall back to searching other locations, starting with `LD_LIBRARY_PATH`.  `auditwheel` supports a similar approach when trying to find dependencies, and it makes it a whole lot easier to find and include third-party libraries. Is there any reason this sort of thing couldn't be added to `delocate`? Happy to send a pull request your way.

**Comment by matthew-brett** [comment]
Yes, sure, a pull request would be welcome.

**Comment by fbrennen** [comment]
(still happy to work on this if you see any improvements needed to the PR)
