### ISSUE TITLE
Add support for Windows wheels

### ISSUE THREAD

**Issue by ghost** [matthew-brett/delocate#29]
Currently the process of building windows wheels is filled with too many hacks. I propose that delocate support windows in the following way:

1. The wheel is unpacked
2. For each PYD/DLL file in the wheel
   a) identify dependencies
   b) recursively add all dependencies to a list
3. Remove all DLL names that are already in the wheel
4. The remaining list constitutes "missing dependencies." These should be copied into a subfolder
5. For all python packages `AddDllDirectory` should be prepended to `__init__.py` just after the `__future__` imports.

**Comment by xoviat** [comment]
Note that `PyInstaller` [already has][1] this functionality:

```python
    try:
        for a in args.filenames:
            for fn in glob.glob(a):
                imports = PyInstaller.depend.bindepend.getImports(fn)
                if is_win:
                    assemblies = PyInstaller.depend.bindepend.getAssemblies(fn)
                    imports.update([a.getid() for a in assemblies])
                print(fn, imports)
    except KeyboardInterrupt:
        raise SystemExit("Aborted by user request.")
```

We can't copy this functionality because it's GNU, but we could consider adding a dependency on Windows.

[1]: https://github.com/pyinstaller/pyinstaller/blob/79c881a2dd2c37965f46c337c59d2ce475e79274/PyInstaller/utils/cliutils/bindepend.py#L41-L50

**Comment by anthrotype** [comment]
I was also wondering if there’s an equivalent of delocate or auditwheel for Windows, so stumbled on this. Did anything happen since then? (Unfortunately I’m not a Windows user so I can’t be of help.)

**Comment by adang1345** [comment]
See https://github.com/adang1345/delvewheel, which is an equivalent for Windows that I wrote.

**Comment by jvolkman** [comment]
@HexDecimal this issue is referring to delocating windows wheels, not delocating macos wheels on windows. As mentioned above, `delvewheel` exists now for the former so maybe you can close this issue.

**Comment by HexDecimal** [comment]
You're right. I guess I was always confused by the title. I'll close this since Delocate is setup specially to handle MacOS wheels and the changes needed to support other platforms would be equivalent to writing and entire new tool, which has been done already as stated.
