### ISSUE TITLE
Disable cron, or reduce number of Mac jobs in the build matrix

### ISSUE THREAD

**Issue by BanzaiMan** [matthew-brett/delocate#31]
In https://travis-ci.org/matthew-brett/delocate/builds, you will notice that some builds have been canceled. This is due to our mitigation efforts related to https://www.traviscistatus.com/incidents/mc9x2wmpnvhg.

During the incident, we noticed that the daily cron job creates 10 Mac jobs, which often do not finish before the next day's cron job starts. As a result, the jobs will always fall behind the schedule, adding significant load on our system.

Please consider disabling the cron job.

Thank you.

**Comment by matthew-brett** [comment]
Thanks for the reminder.  Actually, we really only need to check every time the images change.  Is there a good way to trigger builds when that happens?

**Comment by BanzaiMan** [comment]
There is no mechanism to do that at the moment, I'm afraid.

**Comment by matthew-brett** [comment]
I've dropped the frequency to weekly - is that OK?

**Comment by BanzaiMan** [comment]
Yes. That is reasonable.
