### ISSUE TITLE
delocate-wheel can't add dylibs and so files

### ISSUE THREAD

**Issue by polychordlondon** [matthew-brett/delocate#49]
I'm trying to build a wheel for MacOS users, the source code of this wheel can be found here:
https://github.com/PolyChord/PolyChordLite/tree/setup_pip

I'm facing the same problem than [issue#15](https://github.com/matthew-brett/delocate/issues/15):

    ➜  polychordlite git:(setup_pip) delocate-listdeps --all --depending dist/pypolychord_nompi-1.15.1-cp27-cp27m-macosx_10_12_x86_64.whl                                                                        
    /Users/polychord/Desktop/polychordlite/pypolychord/lib/libchord.so:
        _pypolychord.so
    /usr/lib/libSystem.B.dylib:
        _pypolychord.so
    /usr/local/Cellar/gcc/8.2.0/lib/gcc/8/libgcc_s.1.dylib:
        _pypolychord.so
    /usr/local/Cellar/gcc/8.2.0/lib/gcc/8/libgfortran.5.dylib:
        _pypolychord.so
    /usr/local/Cellar/gcc/8.2.0/lib/gcc/8/libstdc++.6.dylib:
        _pypolychord.so

    ➜  polychordlite git:(setup_pip) delocate-wheel  -w dist/fixed -v dist/pypolychord_nompi-1.15.1-cp27-cp27m-macosx_10_12_x86_64.whl                                                                           
    Fixing: dist/pypolychord_nompi-1.15.1-cp27-cp27m-macosx_10_12_x86_64.whl

Nothing is added to the fixed wheel.

But I think that the architecture is fine (architecture of the wheel):

    _pypolychord.so
    pypolychord
        __init__.py
        output.py
        priors.py
        settings.py
    pypolychord_nompi-1.15.1.dist-info
        ...

The wheels can be built on linux with auditwheel.

Python 2.7 - delocate 0.7.4 - MacOS 10.12.6 (VM)

**Comment by zhreshold** [comment]
+1, same behavior here, with `-v` it shows `Fixing: dist/xxx.whl` but nothing happens
