### ISSUE TITLE
wheeltools on windows creates zip files with backslashes

### ISSUE THREAD

**Issue by isuruf** [matthew-brett/delocate#50]
I'm using wheeltools to move some dll files into the wheel and I use `wheeltools.InWheel` to do that. Resulting wheel has backslashes `\` instead of `/` in path separators and therefore when opening this wheel in Linux, the directory structure is gone. PyPI refuses to accept this modified wheel.
(As a workaround I'm decompressing the wheel file and archive the contents using `7z` and it works.)

Here's what I do, https://github.com/symengine/symengine-wheels/blob/709f8ee0ac687b9e8e4c0383b9a309d3c88a165a/fix_windows_wheel.py#L11-L18

**Comment by matthew-brett** [comment]
I hate to ask - but did you see where in the code that is happening?  I'm happy to put in a fix ...

**Comment by isuruf** [comment]
I think it was https://github.com/matthew-brett/delocate/blob/138203f4784f95d114d29a4e555dfd984eccf4c2/delocate/tools.py#L379.
