### ISSUE TITLE
delocate-wheel does not work for pybind11 project?

### ISSUE THREAD

**Issue by kozo2** [matthew-brett/delocate#52]
I used delocate-wheel for our project
https://github.com/ecell/ecell4-base/blob/v2.0/azure-pipelines.yml

The wheel file is https://www.dropbox.com/s/bwoqf0rdonief6l/ecell4_base-1.0.0-cp37-cp37m-macosx_10_14_x86_64.whl?dl=0

But delocate-wheel -v did not fix any dylib.

```
hoges-mbp:Downloads hoge$ ~/miniconda3/bin/delocate-wheel -v ecell4_base-1.0.0-cp37-cp37m-macosx_10_14_x86_64.whl 
Fixing: ecell4_base-1.0.0-cp37-cp37m-macosx_10_14_x86_64.whl
hoges-mbp:Downloads hoge$ ~/miniconda3/bin/delocate-listdeps ecell4_base-1.0.0-cp37-cp37m-macosx_10_14_x86_64.whl 
/usr/local/opt/boost/lib/libboost_regex-mt.dylib
/usr/local/opt/boost/lib/libboost_unit_test_framework-mt.dylib
/usr/local/opt/gsl/lib/libgsl.23.dylib
/usr/local/opt/gsl/lib/libgslcblas.0.dylib
/usr/local/opt/hdf5/lib/libhdf5.103.dylib
/usr/local/opt/hdf5/lib/libhdf5_cpp.103.dylib
/usr/local/opt/szip/lib/libsz.2.dylib
hoges-mbp:Downloads hoge$ ~/miniconda3/bin/delocate-wheel -v ecell4_base-1.0.0-cp37-cp37m-macosx_10_14_x86_64.whl 
Fixing: ecell4_base-1.0.0-cp37-cp37m-macosx_10_14_x86_64.whl
hoges-mbp:Downloads hoge$ ~/miniconda3/bin/delocate-listdeps ecell4_base-1.0.0-cp37-cp37m-macosx_10_14_x86_64.whl 
/usr/local/opt/boost/lib/libboost_regex-mt.dylib
/usr/local/opt/boost/lib/libboost_unit_test_framework-mt.dylib
/usr/local/opt/gsl/lib/libgsl.23.dylib
/usr/local/opt/gsl/lib/libgslcblas.0.dylib
/usr/local/opt/hdf5/lib/libhdf5.103.dylib
/usr/local/opt/hdf5/lib/libhdf5_cpp.103.dylib
/usr/local/opt/szip/lib/libsz.2.dylib
hoges-mbp:Downloads hoge$ ~/miniconda3/bin/delocate-wheel --version
delocate-wheel 0.7.4
hoges-mbp:Downloads hoge$ 

```

Our project is using pybind11.

Do you have any idea about this?

**Comment by rgommers** [comment]
@kozo2 did you get any more insights into this? Is `pybind11` really the cause here?

**Comment by matthew-brett** [comment]
Is it possible this is an example of #15?   Delocate doesn't currently fix single-file modules that don't have package directories.   See #39 for a proposed fix - but I've been slow to get to the problem - I'm not quite happy with the architecture.

**Comment by kozo2** [comment]
> did you get any more insights into this?
@rgommers No. Since we moved from wheel to conda package, I close this issue. I don't know that it was really caused by 'pybind11'.
@matthew-brett I'm sorry, I close this issue.  I can't take time for finding the cause of this issue.

Sorry for bothering you.

**Comment by matthew-brett** [comment]
No problem - I'm sure you'll lose some users, by not having pip, but it's true the delocate won't do what you want at the moment.
