### ISSUE TITLE
Case change for "object is not a Mach-O file type" in cctools-949.0.1

### ISSUE THREAD

**Issue by atwilso** [matthew-brett/delocate#57]
In tools.py line 165, we expect the string 'Object is not a Mach-O file type' as an error from `otool`.   As of ctools-949.0.1 we're getting back 'object is not a Mach-O file type'.  The difference in capitalization causes the test to fail and delocate errors out.

The cleanest fix is to add another line to the `BAD_OBJECT_TESTS` table in tools.py.  I'll fork the repository, do this, and submit a pull request.

**Comment by matthew-brett** [comment]
Great - thanks.

**Comment by matthew-brett** [comment]
I think this was fixed by #58 - please re-open if I'm wrong.
