### ISSUE TITLE
DelocationError: library [...] does not exist

### ISSUE THREAD

**Issue by neothemachine** [matthew-brett/delocate#6]
I'm currently trying to produce Mac OS X wheels for one of my libraries ([rawpy](https://github.com/neothemachine/rawpy), a wrapper around [libraw](http://www.libraw.org/)) using Travis CI. I adjusted everything so that it builds libraw as universal binary and this seems to work. Note that I don't have a Mac so I'm relying on what Travis tells me. When using delocate to put libraw into the wheel I get the following error:

```
delocate.delocating.DelocationError: library "/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpbZZbgl/wheel/libraw_r.10.dylib" does not exist
```

listdeps says:
```
$ delocate-listdeps dist/*.whl
/Users/travis/build/neothemachine/rawpy-mac-wheels/rawpy/libraw_r.10.dylib
```

The build is here: https://travis-ci.org/neothemachine/rawpy-mac-wheels/jobs/37689337

I'm not sure where the actual error is, probably not in delocate. The path which `delocate-listdeps` shows is strange, as this is not the location where the dylib ends up. It should point to:

```
/Users/travis/build/neothemachine/rawpy-mac-wheels/rawpy/external/LibRaw/cmake_build/install/lib/libraw_r.10.dylib
```

What may be relevant is the following cmake warning when building libraw:
```
Policy CMP0042 is not set: MACOSX_RPATH is enabled by default. Run "cmake
--help-policy CMP0042" for policy details. Use the cmake_policy command to
set the policy and suppress this warning.
MACOSX_RPATH is not specified for the following targets:
raw
raw_r
```

Any idea?

**Comment by matthew-brett** [comment]
Closing as resolved by #8, please re-open if you disagree.
