### ISSUE TITLE
delocate fails when LC_RPATH is set to @loader_path

### ISSUE THREAD

**Issue by chatziko** [matthew-brett/delocate#62]
Using a lib from [ortools](https://github.com/google/or-tools/releases/download/v7.4/or-tools_MacOsX-10.14.6_v7.4.7247.tar.gz)
```
$ otool -l libClp.1.14.3.dylib
...
          cmd LC_RPATH
      cmdsize 32
         path @loader_path (offset 12)
```
`delocate-wheel` is confused, searching for a directory names "@loader_path"
```
$ delocate-wheel dist/*

/usr/local/lib/python3.7/site-packages/delocate/libsana.py:110: UserWarning: Couldn't find @rpath/libClp.1.dylib on paths:
	/tmp/dist/@loader_path
  '\n\t'.join(realpath(path) for path in rpaths),
```

Same thing with:
```
          cmd LC_RPATH
      cmdsize 24
         path $ORIGIN (offset 12)
```

**Comment by matthew-brett** [comment]
That's right, I'm afraid, we don't deal with @loader_path at the moment.   I guess @loader_path is always the path containing the library expressing the dependencies.

**Comment by chatziko** [comment]
Hacky workaround for anyone interested: create a symlink named `@loader_path` (the exact path is shown in the error message) to wherever the library is! `delocate-wheel` will happily follow it and find the library :smile:
