### ISSUE TITLE
Is there a way to exclude a specific library?

### ISSUE THREAD

**Issue by crisluengo** [matthew-brett/delocate#77]
I have a package that depends, besides a few other things, on libjvm.dylib, because it needs to call some Java code. But we need to use the user's Java installation, which is more than just one library. The module goes through some trouble to locate the user's libjvm.dylib. So including it in the package is not intended.

Ideally there would be a way to exclude a library from being delocated. Just like system libraries are being excluded, we'd be able to add some other libraries to that list.

A colleague found a way to do this with auditwheel: https://github.com/DIPlib/diplib/blob/pydip-experimental/pydip/setup/auditwheel

**Comment by matthew-brett** [comment]
You'd have to do this from a Python script, calling Delocate's functions.  Have a look at https://github.com/matthew-brett/delocate/blob/master/delocate/cmd/delocate_wheel.py#L69 and https://github.com/matthew-brett/delocate/blob/master/delocate/delocating.py#L304 . You need to craft a suitable 'copy_filt_func` function - maybe something like:

```python
def no_java(libname):
    if not filter_system_libs(libname):
        return False
    return os.path.basename(libname) != 'libjvm.dylib'
```

**Comment by WillAyd** [comment]
A few years later than the OP but I believe this is resolved by https://github.com/matthew-brett/delocate/pull/106
