### ISSUE TITLE
Cannot delocate /usr/local/lib/libgmp.10.dylib from Homebrew

### ISSUE THREAD

**Issue by msabramo** [matthew-brett/delocate#9]
I suspect I am misunderstanding what `delocate` can do or how it works.

I'm trying to fix up a `pandoc` executable so that it no longer depends on `/usr/local/lib/libgmp.10.dylib` from my Homebrew installation.

```console
[marca@marca-mac2 pypandoc]$ tree vendor
vendor
└── pandoc
    └── darwin
        └── pandoc

2 directories, 1 file
[marca@marca-mac2 pypandoc]$ otool -L vendor/pandoc/darwin/pandoc
vendor/pandoc/darwin/pandoc:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/lib/libgmp.10.dylib (compatibility version 13.0.0, current version 13.0.0)
[marca@marca-mac2 pypandoc]$ delocate-listdeps --depending vendor/pandoc/darwin
/usr/local/Cellar/gmp/6.0.0a/lib/libgmp.10.dylib:
    vendor/pandoc/darwin/pandoc
[marca@marca-mac2 pypandoc]$ delocate-path vendor/pandoc/darwin
[marca@marca-mac2 pypandoc]$ tree vendor
vendor
└── pandoc
    └── darwin
        └── pandoc

2 directories, 1 file
[marca@marca-mac2 pypandoc]$ otool -L vendor/pandoc/darwin/pandoc
vendor/pandoc/darwin/pandoc:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/lib/libgmp.10.dylib (compatibility version 13.0.0, current version 13.0.0)
[marca@marca-mac2 pypandoc]$ delocate-listdeps --depending vendor/pandoc/darwin
/usr/local/Cellar/gmp/6.0.0a/lib/libgmp.10.dylib:
    vendor/pandoc/darwin/pandoc
```

So it looks like nothing happened.

Does `delocate` not work on executables (only libraries and wheels) perhaps?

**Comment by matthew-brett** [comment]
Good guess, yes, the script version uses the default for the underlying Python routine, which is to check only things that match a path filter for dynamic libraries.

I think you would get the result you want if you script from Python with something like:

```
from delocate import delocate_path
delocate_path('vendor/pandoc/darwin', 'lib/output/path', lib_filt_func=None)
```

`lib_filt_func = None` switches off the default library extension checks.  Does that work?

It would be very easy to add a flag to do that in the `delocate-path` script.  What do you think the flag should be called?

It would be easy

**Comment by msabramo** [comment]
```
In [1]: from delocate import delocate_path

In [2]: delocate_path('vendor/pandoc/darwin/bin', 'vendor/pandoc/darwin/lib', lib_filt_func=None)
Out[2]: {u'/usr/local/Cellar/gmp/6.0.0a/lib/libgmp.10.dylib': {'/Users/marca/dev/git-repos/pypandoc/vendor/pandoc/darwin/bin/pandoc': u'/usr/local/lib/libgmp.10.dylib'}}
```

```
$ tree vendor/pandoc/darwin
vendor/pandoc/darwin
├── bin
│   └── pandoc
└── lib
    └── libgmp.10.dylib

$ otool -L vendor/pandoc/darwin/bin/pandoc
vendor/pandoc/darwin/bin/pandoc:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	@loader_path/../lib/libgmp.10.dylib (compatibility version 13.0.0, current version 13.0.0)
```

Is there a reason to have a flag and not just make it the default behavior? Is there something bad that could happen if it patched my executable and I wasn't expecting that?

Alternatively, what if it automatically does the `lib_filt_func=None` behavior if I specify the path to a file that is an executable binary -- e.g.:

```
$ delocate-path vendor/pandoc/darwin/pandoc
```

Something like:

```python
    if os.path.isfile(tree_path) and os.access(tree_path, os.X_OK):
        lib_filt_func = None
```

I think the `tree_libs` function needs to change a bit too, but you get the basic idea I think.

**Comment by matthew-brett** [comment]
You're right, I can't think of anything bad that would happen if the default was to check all files for dependent libraries, other than the process being a little slower.  I suspect the difference would be pretty small, but I'll check.

**Comment by matthew-brett** [comment]
That took a while for me to get to.   Here's a test checking for library dependencies on an unpacked scipy wheel in `dist/tmp`:

```
In [2]: from delocate import tree_libs

In [3]: from delocate.delocating import _dylibs_only

In [4]: timeit tree_libs('dist/tmp', None)
1 loops, best of 3: 9.19 s per loop

In [5]: timeit tree_libs('dist/tmp', _dylibs_only)
1 loops, best of 3: 1.01 s per loop
```

So, it does make rather a large difference in this case.

Given this is about the largest case that is likely at least for a Python wheel, and that the command only gets run once by the packager, maybe it is still reasonable to have 'check everything' as the default, and have a flag to only check paths that look like dynamic libs (the current default behavior).

**Comment by matthew-brett** [comment]
Any chance you could cast a quick eye over https://github.com/matthew-brett/delocate/pull/10 ?
